spring:
  application:
    name: GestionHotel-Core
  datasource:
    url: jdbc:h2:file:~/almacenDB
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false