spring:
  application:
    name: GestionHotel-Core
  datasource:
    url: jdbc:h2:file:~/almacenDB
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  rsocket:
    server:
      port: 7000