server:
  port: 8980

spring:
  application:
    name: msvc-almacen
  datasource:
    url: jdbc:h2:file:~/almacenDB
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/